### ISSUE TITLE
Crash on Elite

### ISSUE THREAD

**Issue by STSsadoni** [fiiiiilth/BeakedTheCultist-StS#12]
Tried to enter an elite fight, and I got a crash related to the Beaked mod.  Not sure if it's actually your guys' fault, but here's the crash log.

04:14:46.683 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=saves\THE_CURSED.autosave
04:14:46.686 INFO dungeons.AbstractDungeon> ELITE: beaked:SuperParasite
04:14:46.690 INFO helpers.MonsterHelper> Unspecified key: beaked:SuperParasite in MonsterHelper.
04:14:46.693 INFO helpers.File> Successfully saved file=F:\SteamLibrary\steamapps\common\SlayTheSpire\preferences\THE_CURSED
04:14:46.693 INFO helpers.FileSaver> Dequeue: qsize=0 file=saves\THE_CURSED.autosave
04:14:46.694 INFO helpers.File> Attempting to save file=F:\SteamLibrary\steamapps\common\SlayTheSpire\saves\THE_CURSED.autosave

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError04:14:46.726 INFO helpers.File> Successfully saved file=F:\SteamLibrary\steamapps\common\SlayTheSpire\saves\THE_CURSED.autosave

	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ExceptionInInitializerError
	at beaked.Beaked.lambda$receivePostInitialize$13(Beaked.java:312)
	at basemod.BaseMod.lambda$addMonster$1(BaseMod.java:1324)
	at basemod.BaseMod.getMonster(BaseMod.java:1345)
	at basemod.patches.com.megacrit.cardcrawl.helpers.MonsterHelper.GetEncounter.Postfix(GetEncounter.java:17)
	at com.megacrit.cardcrawl.helpers.MonsterHelper.getEncounter(MonsterHelper.java:571)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getEliteMonsterForRoomCreation(AbstractDungeon.java:2391)
	at com.megacrit.cardcrawl.rooms.MonsterRoomElite.onPlayerEntry(MonsterRoomElite.java:83)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2320)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2182)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2849)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2537)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NullPointerException
	at beaked.monsters.SuperParasite.<clinit>(SuperParasite.java:189)
	... 15 more

**Comment by STSsadoni** [comment]
Got another one.


Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ExceptionInInitializerError
	at beaked.Beaked.lambda$receivePostInitialize$13(Beaked.java:312)
	at basemod.BaseMod.lambda$addMonster$1(BaseMod.java:1324)
	at basemod.BaseMod.getMonster(BaseMod.java:1345)
	at basemod.patches.com.megacrit.cardcrawl.helpers.MonsterHelper.GetEncounter.Postfix(GetEncounter.java:17)
	at com.megacrit.cardcrawl.helpers.MonsterHelper.getEncounter(MonsterHelper.java:571)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getEliteMonsterForRoomCreation(AbstractDungeon.java:2391)
	at com.megacrit.cardcrawl.rooms.MonsterRoomElite.onPlayerEntry(MonsterRoomElite.java:83)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2320)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2182)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2849)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2537)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NullPointerException
	at beaked.monsters.SuperParasite.<clinit>(SuperParasite.java:189)
	... 15 more06:11:18.179 INFO helpers.File> Successfully saved file=F:\SteamLibrary\steamapps\common\SlayTheSpire\saves\THE_DUELIST.autosave
