### ISSUE TITLE
error? how to fix?

### ISSUE THREAD

**Issue by geraldloo** [fiiiiilth/BeakedTheCultist-StS#4]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:34)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:245)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at basemod.BaseMod.initializeEncounters(BaseMod.java:611)
	at basemod.BaseMod.initialize(BaseMod.java:342)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.megacrit.cardcrawl.helpers.MonsterHelper.<clinit>(MonsterHelper.java:89)
	... 16 more

**Comment by Moocowsgomoo** [comment]
Does this still occur with the most recent versions of BaseMod and the Beaked?
